name: build, e2e
run-name: test
on:
  push:
    branches: '**'
  pull_request:
    branches: 'master'

env:
  MONGO_URI: ${{ secrets.MONGO_URI }}
  MONGO_DB_NAME: ${{ secrets.MONGO_DB_NAME }}

jobs:
  Pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 20.x ]

    steps:
      - uses: actions/checkout@v2
      - name: Echo GitHub secret
        run: echo "My GitHub secret is ${{ secrets.MONGO_URI }}"
      - name: Echo var secret
        run: echo "My GitHub var is ${{ vars.BOLT }}"
      - name: Echo var2 secret
        run: echo "My GitHub var2 is ${{ vars.BOLT_DVA }}"
      - name: Starting Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install modules
        run: yarn install
      - name: build production dist
        run: yarn tsc
        if: always()
      - name: run e2e tests
        run: yarn test:e2e
        if: always()
